/* Automatically generated by './build/build-entry.js' */
import Alert from '../packages/alert/index.js';
import Switch from '../packages/switch/index.js';
import Spin from '../packages/spin/index.js';
import Split from '../packages/split/index.js';
const components = [
  Alert,
  Switch,
  Spin,
  Split,
];
const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
  Vue.prototype.$Spin = Spin;
  Vue.prototype.$LIPEI = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };
};
/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}
export default {
  install,
  Alert,
  Switch,
  Spin,
  Split
};
