/* Automatically generated by './build/build-entry.js' */
import Switch from '../packages/switch/index.js';
import Spin from '../packages/spin/index.js';
import Split from '../packages/split/index.js';
import Affix from '../packages/affix/index.js';
import Button from '../packages/button/index.js';
import Modal from '../packages/modal/index.js';
const components = [
  Switch,
  Spin,
  Split,
  Affix,
  Button,
  Modal,
];
const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
  Vue.prototype.$Spin = Spin;
  Vue.prototype.$Modal = Modal;
  Vue.prototype.$LIPEI = {
    size: opts.size || '',
    transfer: 'transfer' in opts ? opts.transfer : '',
    zIndex: opts.zIndex || 2000,
    modal:{
      maskClosable: opts.modal ? 'maskClosable' in opts.modal ? opts.modal.maskClosable : '' : ''
    }
  };
};
/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}
export default {
  install,
  Switch,
  Spin,
  Split,
  Affix,
  Button,
  Modal
};
