/* Automatically generated by './build/build-entry.js' */
import Alert from '../packages/alert/index.js';
import Switch from '../packages/switch/index.js';
const components = [
  Alert,
  Switch,
];
const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};
/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}
export default {
  install,
  Alert,
  Switch
};
